name: Live Data Collector

on:
  schedule:
    - cron: "0 * * * *" # Every hour at 00 minutes
  workflow_dispatch: # Allow manual run from GitHub Actions tab

jobs:
  collect-data:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        attempt: [1, 2, 3]  # Retry job up to 3 times

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run data collector
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_KEY: ${{ secrets.SUPABASE_SERVICE_KEY }}
        run: |
          python src/live_data_collector.py
